# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
# vim: nospell

resolver: lts-8.0

packages:
- '.'

extra-deps:
- 'accelerate-1.0.0.0'
- 'accelerate-io-1.0.0.0'
- 'accelerate-llvm-1.0.0.0'
- 'accelerate-llvm-native-1.0.0.0'
- 'accelerate-llvm-ptx-1.0.0.0'
- 'chaselev-deque-0.5.0.5'
- 'cuda-0.7.5.3'
- 'lens-accelerate-0.1.0.0'
- 'libffi-0.1'
- 'linear-accelerate-0.3'
- 'llvm-hs-4.0.0.0'
- 'llvm-hs-pure-4.0.0.0'
- 'mwc-random-accelerate-0.1.0.0'
- 'normaldistribution-1.1.0.3'
- 'unique-0'


# Override default flag values for local packages and extra-deps
flags:
  llvm-hs:
    shared-llvm: true
  accelerate:
    debug: true
    ekg:   false
  accelerate-llvm-native:
    debug: true
  accelerate-llvm-ptx:
    debug: true
    nvvm:  false
  mhnn-accelerate:
    llvm-cpu: true
    llvm-ptx: false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

